services:
  api:
    build: .
    container_name: minipos-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - minipos_data:/app/data

volumes:
  minipos_data:
